Switch to emitting function based generators.
- Required refactoring the html5 generators to make the resulting
  functions smaller in order to avoid the "Method code too large"
  error: removed opt-space from output and combined some of the tag
  components into single strings.